# Drilling and Tapping

You will need to drill and tap holes into the aluminum extrusion. As this is not a handyman writeup but instead a 3D printer build instruction, I'll skip over  _how_ and focus on _what_.

## Materials

- [ ] 4 x 2040 Extrusion @ 500mm - Uprights
- [ ] 8 x 2020 Extrusion @ 500mm - Top and Bottom sides
- [ ] 1 x 2020 Extrusion @ 600mm - X Axis
- [ ] 2 x 2020 Extrusion @ 450mm - Bed Platform
- [ ] 2 x 2020 Extrusion @ 500mm - Bed Platform

### Uprights
**2040 Extrusion 500mm**
- Using an M5 tap, create threads for both center holes on one side and only one of the center holes on the other side. (3 tapped center holes)

![image](https://user-images.githubusercontent.com/17118188/117879896-79d74180-b275-11eb-88b6-ba3437c32fc7.png)

### Top and Bottom Sides (only six pieces, leave 2 for later)
**2020 Extrusions 500mm**
- Drill an M5 hole in six of the 2020 500mm extrusions 10mm from either of the edges.

![image](https://user-images.githubusercontent.com/17118188/117879940-88bdf400-b275-11eb-8266-2fc0a74d500a.png)

### X-Axis
**2020 Extrusion 600mm**
- From the left side, drill two M5 holes: one at 22mm and the other at 65mm. 
- From the right side, drill two  M5 holes: one at 25mm and the other at 65mm from the right edge.

![image](https://user-images.githubusercontent.com/17118188/117879971-91162f00-b275-11eb-8696-79545c287823.png)

### Bed Platform

Before we do the bed platform you will need to measure the distance from the center of the holes of your heated bed. This measurement will dictate where the holes will be that you need to drill. In my case, I measured **240mm**, so that's the value I'll use here.

**2020 Extrusion 500mm**
- Drill an M5 hole 10mm from either edge on both pieces. (2 holes total per piece)
- Drill an M4 hole 130mm from either edge. (Formula used: Bed Holes = 240mm apart; Length = 500mm, so remainder = 260mm / 2 = 130mm) This hole will be used for the bed screws.

(In the below picture, do NOT drill into your heated bed, this picture simply indciates where the holes are referred to above)

![image](https://user-images.githubusercontent.com/17118188/117880161-cae73580-b275-11eb-9726-ac18047b09f3.png)

**2020 Extrusion 450mm**
- Drill two M5 holes at 10mm and at 30mm from the left edge and repeat from the right edge. (4 holes total per piece)
- Rotate the extrusion so the new holes will be perpendicular to the holes you have already drilled. (IE: The holes you drilled before should go front to back while the next set of holes are top to bottom)
- Drill two M5 holes 105mm from each side. (Formula used: Bed Holes = 240mm, so 450mm length - 240mm holes = 210mm / 2 = 105mm)
 
![image](https://user-images.githubusercontent.com/17118188/117880333-fcf89780-b275-11eb-8e1b-27f85f03f4d2.png)

And that's all there is to drill and tap. Next you can start with the actual frame construction.